#
# Module manifest for ps-script-machine module
#
# Generated by: ps-script-machine contributors
#
# Generated on: 2025-01-01
#

@{
    RootModule           = 'ps-script-machine.psm1'
    ModuleVersion        = '1.0.0'
    GUID                 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'
    Author              = 'ps-script-machine contributors'
    CompanyName         = 'ps-script-machine'
    Copyright           = '(c) 2025 ps-script-machine. MIT license.'
    Description          = 'PowerShell/PowerCLI development platform for VMware vSphere administrators. Provides reusable functions, templates, and quality assurance for coding agents.'
    PowerShellVersion    = '7.4'
    PowerShellHostName   = 'ConsoleHost'
    PowerShellHostVersion = '7.4'
    DotNetFrameworkVersion = '8.0'
    ClrVersion           = '8.0'
    # Explicit export list - only public functions are exported.
    # Private functions are tested via InModuleScope, not via FunctionsToExport.
    FunctionsToExport    = @(
        'Get-CdpNetworkInfo',
        'Get-VMHostNetworkInfo',
        'Export-ModuleData',
        'Select-VIServerTarget',
        'Connect-MultiVIServer'
    )
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @()
    DscResourcesToExport = @()
    ModuleList           = @()
    FileList             = @()
    # PowerCLI is declared as an external dependency, not as a RequiredModule.
    # This allows the module to be imported and unit-tested (with mocks) even
    # when PowerCLI is not installed.  PowerCLI is only needed for actual
    # vSphere operations.
    RequiredModules      = @()
    RequiredAssemblies   = @()
    NestedModules        = @()
    HelpInfoURI          = 'https://github.com/spiral023/ps-script-machine'
    DefaultCommandPrefix = ''
    PrivateData          = @{
        PSData = @{
            Tags         = @('VMware', 'PowerCLI', 'vSphere', 'Automation', 'DevOps', 'Pester', 'PSScriptAnalyzer')
            LicenseUri   = 'https://github.com/spiral023/ps-script-machine/blob/main/LICENSE'
            ProjectUri   = 'https://github.com/spiral023/ps-script-machine'
            IconUri      = ''
            ReleaseNotes = 'Initial release of ps-script-machine development platform.'
            Prerelease   = ''
            # PowerCLI is an external module dependency - it is required for
            # runtime vSphere operations but not for module import or unit
            # testing (where PowerCLI cmdlets are mocked).
            ExternalModuleDependencies = @('VMware.PowerCLI')
        }
    }
}